[phases.setup]
aptPkgs = [
    "libx11-6",
    "libxext6", 
    "libxrender1",
    "libxtst6",
    "libxi6",
    "libglib2.0-0",
    "libgtk-3-0",
    "libsm6",
    "libice6",
    "libxrandr2",
    "libxss1",
    "libxcomposite1",
    "libxdamage1",
    "libxfixes3",
    "libcairo-gobject2",
    "libgdk-pixbuf2.0-0",
    "libpango-1.0-0",
    "libharfbuzz0b",
    "libfontconfig1",
    "libfreetype6"
]
